import { ItemCategory, DecorationType } from './itemDefinitions.js'; 

export const AchievementType = {
  MESSAGES_SENT: 'messages_sent',
  VOICE_TIME: 'voice_time',
  LOOTBOX_OPENED: 'lootbox_opened',
  ITEM_COLLECTED: 'item_collected',
  DAILY_STREAK: 'daily_streak',
  PREMIUM_ACQUIRED: 'premium_acquired',
  TITLE_SET: 'title_set',
};

const achievementDefinitions = {
  'msg_100': {
    id: 'msg_100',
    name: 'Болтун I',
    description: 'Отправить 100 сообщений на сервере',
    type: AchievementType.MESSAGES_SENT,
    threshold: 100,
    reward: { stars: 50 },
    medalEmoji: '💬',
    secret: false,
  },
  'msg_1000': {
    id: 'msg_1000',
    name: 'Болтун II',
    description: 'Отправить 1000 сообщений на сервере',
    type: AchievementType.MESSAGES_SENT,
    threshold: 1000,
    reward: { stars: 200, shards: 1 },
    medalEmoji: '🗣️',
    secret: false,
  },
  'voice_1h': {
    id: 'voice_1h',
    name: 'Душа компании I',
    description: 'Провести 1 час в активных голосовых каналах',
    type: AchievementType.VOICE_TIME,
    threshold: 3600,
    reward: { stars: 75 },
    medalEmoji: '🎙️',
    secret: false,
  },
  'voice_10h': {
    id: 'voice_10h',
    name: 'Душа компании II',
    description: 'Провести 10 часов в активных голосовых каналах',
    type: AchievementType.VOICE_TIME,
    threshold: 36000,
    reward: { stars: 300, shards: 2 },
    medalEmoji: '🎧',
    secret: false,
  },
  'open_mythic_lootbox': { 
    id: 'open_mythic_lootbox',
    name: 'Легендарный Искатель',
    description: 'Открыть свой первый Мифический Ларец',
    type: AchievementType.LOOTBOX_OPENED,
    criteria: { lootboxId: 'lootbox_mythic' },
    threshold: 1,
    reward: { shards: 5, itemId: 'luck_clover_medium', quantity: 1 },
    medalEmoji: '🌌',
    secret: true,
  },
  'daily_streak_7': {
    id: 'daily_streak_7',
    name: 'Неделя с нами!',
    description: 'Получить 7 ежедневных наград подряд',
    type: AchievementType.DAILY_STREAK,
    threshold: 7,
    reward: { stars: 250, itemId: 'lootbox_silver', quantity: 1 },
    medalEmoji: '📅',
    secret: false,
  },
  'msg_5000': {
    id: 'msg_5000',
    name: 'Болтун III',
    description: 'Отправить 5000 сообщений на сервере',
    type: AchievementType.MESSAGES_SENT,
    threshold: 5000,
    reward: { stars: 1000, shards: 5 },
    medalEmoji: '📢',
    secret: false,
  },
  'msg_master': {
    id: 'msg_master',
    name: 'Магистр Слов',
    description: 'Отправить 10,000 сообщений. Вы истинный гуру общения',
    type: AchievementType.MESSAGES_SENT,
    threshold: 10000,
    reward: { stars: 2500, shards: 10, itemId: 'title_token', quantity: 1 },
    medalEmoji: '✍️',
    secret: true,
  },
  'voice_50h': {
    id: 'voice_50h',
    name: 'Легенда Эфира',
    description: 'Провести 50 часов в активных голосовых каналах',
    type: AchievementType.VOICE_TIME,
    threshold: 50 * 3600,
    reward: { stars: 1500, itemId: 'resource_rare_core', quantity: 1 },
    medalEmoji: '📻',
    secret: false,
  },
  'open_gold_chest': {
    id: 'open_gold_chest',
    name: 'Золотоискатель',
    description: 'Открыть свой первый Золотой Клад',
    type: AchievementType.LOOTBOX_OPENED,
    criteria: { lootboxId: 'lootbox_gold' }, 
    threshold: 1,
    reward: { stars: 100, itemId: 'luck_clover_small', quantity: 1 },
    medalEmoji: '💰',
    secret: false,
  },
  'daily_streak_30': {
    id: 'daily_streak_30',
    name: 'Марафонец',
    description: 'Получить 30 ежедневных наград подряд',
    type: AchievementType.DAILY_STREAK,
    threshold: 30,
    reward: { stars: 1000, itemId: 'lootbox_mythic', quantity: 1 },
    medalEmoji: '🗓️',
    secret: false,
  },
  'premium_subscriber': {
    id: 'premium_subscriber',
    name: 'VIP Клуб',
    description: 'Приобрести или получить Премиум-статус',
    type: AchievementType.PREMIUM_ACQUIRED,
    threshold: 1,
    reward: { shards: 3 },
    medalEmoji: '👑',
    secret: false,
  },
  'title_owner': {
    id: 'title_owner',
    name: 'Своё Имя',
    description: 'Установить свой первый титул в профиле',
    type: AchievementType.TITLE_SET,
    threshold: 1,
    reward: { stars: 50 },
    medalEmoji: '📜',
    secret: false,
  },
  'collector_frames_avatar': {
    id: 'collector_frames_avatar',
    name: 'Коллекционер Рамок',
    description: 'Примерить 3 разные рамки для аватара',
    type: AchievementType.ITEM_COLLECTED,
    criteria: { itemCategory: ItemCategory.PROFILE_ACCENT, decorationType: DecorationType.AVATAR_FRAME, uniqueCount: 3 },
    threshold: 3,
    reward: { stars: 200, itemId: 'resource_uncommon_spark', quantity: 2 },
    medalEmoji: '🖼️',
    secret: true,
  },
  'secret_luck': {
    id: 'secret_luck',
    name: 'Невероятная Удача',
    description: '???',
    type: AchievementType.LOOTBOX_OPENED,
    criteria: { itemIdFromLootbox: 'lootbox_mythic' }, 
    threshold: 1,
    reward: { shards: 25 },
    medalEmoji: '🎰',
    secret: true,
  },
};

export function getAchievementDefinition(achievementId) {
  return achievementDefinitions[achievementId] || null;
}

export function getAllAchievementDefinitions() {
  return achievementDefinitions;
}

export default achievementDefinitions;
